package haladesign.form;

import haladesign.component.LichSuMuaHang;
import haladesign.component.ThemKhachHang;
import haladesign.mainMenu.Main;
import haladesign.model.KhachHang;
import haladesign.service.KhachHangService;
import haladesign.system.GlassPanePopup;
import haladesign.system.Notification;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phương Thảo
 */
public class KhachHang_form extends javax.swing.JPanel {

    private DefaultTableModel model = new DefaultTableModel();
    private final KhachHangService service = new KhachHangService();
    private final Main main;
    private List<KhachHang> listKhachHang = new ArrayList<>();

    public KhachHang_form(Main main) {
        initComponents();
        this.main = main;
        this.listKhachHang = this.service.getKH();
        fillTable();
    }

    public void fillTable() {
        this.model = (DefaultTableModel) tblKhachHang.getModel();
        this.model.setRowCount(0);
        for (KhachHang x : this.listKhachHang) {
            Object[] row = {
                x.getHo_ten(), x.getSo_dien_thoai(), x.getGioi_tinh() ? "Nam" : "Nữ", x.getDiaChi(), x.getNgay_tao()
            };
            this.model.addRow(row);
        }
    }

    void showData(int index) {
        KhachHang kh = this.listKhachHang.get(index);
        txtTen.setText(kh.getHo_ten());
        txtDiaChi.setText(kh.getDiaChi() == null ? "" : kh.getDiaChi());
        txtSdt.setText(kh.getSo_dien_thoai() == null ? "" : kh.getSo_dien_thoai());
        lblNgaytao.setText(String.valueOf(kh.getNgay_tao()));
        lblNgaysua.setText(String.valueOf(kh.getNgay_sua()));
        if (kh.getGioi_tinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
    }

    public KhachHang getKH() {
        int id = this.listKhachHang.get(tblKhachHang.getSelectedRow()).getId();
        KhachHang kh = this.service.getKhachHangById(id);
        kh.setHo_ten(txtTen.getText());
        kh.setSo_dien_thoai(txtSdt.getText());
        kh.setGioi_tinh(rdoNam.isSelected() ? true : false);
        kh.setDiaChi(txtDiaChi.getText());
        kh.setNgay_tao(new Date());
        kh.setNgay_sua(new Date());
        kh.setXoa_mem(0);
        return kh;
    }

    public KhachHang xoaKh() {
        int id = this.listKhachHang.get(tblKhachHang.getSelectedRow()).getId();
        KhachHang kh = this.service.getKhachHangById(id);
        kh.setXoa_mem(1);
        return kh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnThem = new haladesign.swingStyle.ButtonMessage();
        txtSearch = new haladesign.swingStyle.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang = new haladesign.swing.table.Table();
        jPanel2 = new javax.swing.JPanel();
        txtSdt = new haladesign.swingStyle.TextField();
        txtTen = new haladesign.swingStyle.TextField();
        btnSua = new haladesign.swingStyle.ButtonMessage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNgaytao = new javax.swing.JLabel();
        lblNgaysua = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        btnXoa = new haladesign.swingStyle.ButtonMessage();
        btnLSMH = new haladesign.swingStyle.ButtonMessage();
        textAreaScroll1 = new haladesign.swingStyle.TextAreaScroll();
        txtDiaChi = new haladesign.swingStyle.TextArea();
        jLabel1 = new javax.swing.JLabel();
        btnTimKiem = new haladesign.swingStyle.ButtonMessage();

        setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(204, 204, 255));
        btnThem.setText("Thêm khách hàng");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtSearch.setLabelText("Tìm kiếm khách hàng");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Số điện thoại", "Giới tính", "Địa chỉ", "Ngày tạo"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachHang);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtSdt.setLabelText("Số điện thoại");

        txtTen.setLabelText("Họ tên");

        btnSua.setBackground(new java.awt.Color(204, 204, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày tạo");

        jLabel4.setText("Lần sửa gần nhất: ");

        lblNgaytao.setText("   ");

        lblNgaysua.setText(" ");

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoNu);
        rdoNu.setSelected(true);
        rdoNu.setText("Nữ");

        btnXoa.setBackground(new java.awt.Color(204, 204, 255));
        btnXoa.setText("Xóa mềm");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLSMH.setBackground(new java.awt.Color(204, 204, 255));
        btnLSMH.setText("Lịch sử mua hàng");
        btnLSMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLSMHActionPerformed(evt);
            }
        });

        textAreaScroll1.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll1.setLabelText("Địa chỉ");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        textAreaScroll1.setViewportView(txtDiaChi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNu))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNgaysua, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLSMH, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblNgaytao))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNgaysua))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLSMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý khách hàng");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haladesign/icon/search.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ThemKhachHang addKH = new ThemKhachHang(this.main);
        this.main.showForm(addKH);
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        this.showData(tblKhachHang.getSelectedRow());
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (tblKhachHang.getSelectedRow() < 0) {
            Notification notification = new Notification(this.main, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Chưa chọn khách hàng nào!");
            notification.showNotification();
            return;
        }
        if (service.insert(xoaKh())) {
//            JOptionPane.showMessageDialog(this, "Xóa thành công");
            new Notification(this.main, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Xóa thành công").showNotification();
            this.listKhachHang = this.service.getKH();
            fillTable();
        } else {
//            JOptionPane.showMessageDialog(this, "Xóa thất bại");
            new Notification(this.main, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Xóa không thành công").showNotification();
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (tblKhachHang.getSelectedRow() < 0) {
            Notification notification = new Notification(this.main, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Chưa chọn khách hàng nào!");
            notification.showNotification();
            return;
        }
        if (service.insert(getKH())) {
//            JOptionPane.showMessageDialog(this, "Update thành công");
            new Notification(this.main, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Update thành công").showNotification();
            this.listKhachHang = this.service.getKH();
            fillTable();
        } else {
//            JOptionPane.showMessageDialog(this, "Update thất bại");
            new Notification(this.main, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Update không thành công").showNotification();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLSMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLSMHActionPerformed
        // TODO add your handling code here:
        if (tblKhachHang.getSelectedRow() < 0) {
            Notification notification = new Notification(this.main, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Chưa chọn khách hàng nào!");
            notification.showNotification();
            return;
        }
        int id = this.listKhachHang.get(tblKhachHang.getSelectedRow()).getId();
        LichSuMuaHang lsu = new LichSuMuaHang(id);
        GlassPanePopup.showPopup(lsu);
    }//GEN-LAST:event_btnLSMHActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        this.listKhachHang = this.service.searchKhachHang(txtSearch.getText());
        fillTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private haladesign.swingStyle.ButtonMessage btnLSMH;
    private haladesign.swingStyle.ButtonMessage btnSua;
    private haladesign.swingStyle.ButtonMessage btnThem;
    private haladesign.swingStyle.ButtonMessage btnTimKiem;
    private haladesign.swingStyle.ButtonMessage btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNgaysua;
    private javax.swing.JLabel lblNgaytao;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private haladesign.swing.table.Table tblKhachHang;
    private haladesign.swingStyle.TextAreaScroll textAreaScroll1;
    private haladesign.swingStyle.TextArea txtDiaChi;
    private haladesign.swingStyle.TextField txtSdt;
    private haladesign.swingStyle.TextField txtSearch;
    private haladesign.swingStyle.TextField txtTen;
    // End of variables declaration//GEN-END:variables

}
