package haladesign.component;

import haladesign.model.SanPham;
import haladesign.model.SanPhamBienTheKhoa;
import haladesign.model.Size;
import haladesign.service.SanPhamService;
import haladesign.swing.table.TableActionCellRender;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NONG HOANG VU
 */
public class UpdateSanPham extends javax.swing.JPanel {

    private final SanPhamService list;
    private DefaultTableModel tblModel;
    private final List<SanPham> listSanPham;

    public UpdateSanPham(String id) {
        initComponents();
        this.list = new SanPhamService();
        this.listSanPham = this.list.getByIdSanPham(id);
        setOpaque(true);
        init(id);
    }

    private void init(String id) {
        lbID.setText(id);
        setData(id);
        fillSize();
        fillTable();
        updateNameProduct();

    }

    private void updateNameProduct() {
        txtSanPham.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                txtTenBienThe.setText(txtSanPham.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                txtTenBienThe.setText(txtSanPham.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                txtTenBienThe.setText(txtSanPham.getText());
            }

        });
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    private void setData(String id) {
        SanPham sp = this.listSanPham.get(0);
        txtSanPham.setText(sp.getTen_san_pham());
//        txtThuongHieu.setText(sp.getThuong_hieu());
        txtMota.setText(sp.getMo_ta() != null ? sp.getMo_ta() : "");
    }

    private void tableClickRow() {
        this.listSanPham.forEach(sp -> {
            SanPhamBienTheKhoa s = sp.getBienTheList().get(tblSanPhamBienThe.getSelectedRow());
            txtTenBienThe.setText(s.getTenBienThe());
            txtSoLuong.setText(String.valueOf(s.getSoLuong()));
            txtGia.setText(String.valueOf(s.getGia()));
        });
    }

    private void fillSize() {
        DefaultComboBoxModel<Size> cbbModel = new DefaultComboBoxModel<>();
        cbbSize.removeAll();
        cbbSize.setModel(cbbModel);
        this.list.getSize().forEach(size -> {
            cbbModel.addElement(size);
        });
    }

    private void fillTable() {
        tblModel = (DefaultTableModel) tblSanPhamBienThe.getModel();
        tblModel.setRowCount(0);
        Integer[] count = {0};
        this.list.getByIdSanPham(lbID.getText()).forEach(sp -> {
            sp.getBienTheList().forEach(s -> {
                Object[] row = {
                    ++count[0],
                    s.getTenBienThe(),
                    s.getSoLuong(),
                    s.getColor().getLoaiMau(),
                    s.getSize().getLoaiSize(),
                    s.getGia()
                };
                tblModel.addRow(row);
            });
        });
        tblSanPhamBienThe.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        txtSanPham = new haladesign.swingStyle.TextField();
        txtThuongHieu = new haladesign.swingStyle.TextField();
        jScrollPane1 = new haladesign.swing.scroll.ScrollPaneWin11();
        tblSanPhamBienThe = new haladesign.swing.table.Table();
        cbbColor = new haladesign.swingStyle.Combobox();
        txtGia = new haladesign.swingStyle.TextField();
        txtSoLuong = new haladesign.swingStyle.TextField();
        txtTenBienThe = new haladesign.swingStyle.TextField();
        textAreaScroll1 = new haladesign.swingStyle.TextAreaScroll();
        txtMota = new haladesign.swingStyle.TextArea();
        button1 = new haladesign.swingStyle.Button();
        button2 = new haladesign.swingStyle.Button();
        button3 = new haladesign.swingStyle.Button();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbbSize = new haladesign.swingStyle.Combobox();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Mã sản phẩm:");

        lbID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbID.setForeground(new java.awt.Color(153, 153, 153));
        lbID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbID.setText("Auto");

        txtSanPham.setEditable(false);
        txtSanPham.setLabelText("Tên sản phẩm");

        txtThuongHieu.setEditable(false);
        txtThuongHieu.setText("Hala Design");
        txtThuongHieu.setLabelText("Thương hiệu");

        tblSanPhamBienThe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Sản Phẩm", "Số Lượng", "Màu Sắc", "Size", "Giá", "Thao Tác"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamBienThe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamBienTheMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPhamBienThe);
        if (tblSanPhamBienThe.getColumnModel().getColumnCount() > 0) {
            tblSanPhamBienThe.getColumnModel().getColumn(0).setMinWidth(50);
            tblSanPhamBienThe.getColumnModel().getColumn(0).setMaxWidth(50);
            tblSanPhamBienThe.getColumnModel().getColumn(2).setMinWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(2).setMaxWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(3).setMinWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(3).setMaxWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(4).setMinWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(4).setMaxWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(5).setMinWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(5).setMaxWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(6).setMinWidth(120);
            tblSanPhamBienThe.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        cbbColor.setLabeText("Color");

        txtGia.setEditable(false);
        txtGia.setLabelText("Giá");

        txtSoLuong.setEditable(false);
        txtSoLuong.setLabelText("Số lượng");

        txtTenBienThe.setEditable(false);
        txtTenBienThe.setLabelText("Tên biến thể");

        textAreaScroll1.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll1.setLabelText("Mô tả");

        txtMota.setColumns(20);
        txtMota.setRows(5);
        textAreaScroll1.setViewportView(txtMota);

        button1.setBackground(new java.awt.Color(102, 204, 255));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haladesign/icon/plusPrimary.png"))); // NOI18N
        button1.setText("Thêm Biến Thể");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        button2.setBackground(new java.awt.Color(102, 204, 255));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haladesign/icon/save.png"))); // NOI18N
        button2.setText("Lưu");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        button3.setBackground(new java.awt.Color(102, 204, 255));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haladesign/icon/check-mark.png"))); // NOI18N
        button3.setText("Hoàn Thành");
        button3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Danh sách biến thể sản phẩm");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Image");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbbSize.setLabeText("Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(121, 121, 121))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtThuongHieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(txtSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbbSize, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbColor, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                    .addComponent(txtTenBienThe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button1, button2, button3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbID))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenBienThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button1, button2, button3});

    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamBienTheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamBienTheMouseClicked
        tableClickRow();
    }//GEN-LAST:event_tblSanPhamBienTheMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private haladesign.swingStyle.Button button1;
    private haladesign.swingStyle.Button button2;
    private haladesign.swingStyle.Button button3;
    private haladesign.swingStyle.Combobox cbbColor;
    private haladesign.swingStyle.Combobox cbbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbID;
    private haladesign.swing.table.Table tblSanPhamBienThe;
    private haladesign.swingStyle.TextAreaScroll textAreaScroll1;
    private haladesign.swingStyle.TextField txtGia;
    private haladesign.swingStyle.TextArea txtMota;
    private haladesign.swingStyle.TextField txtSanPham;
    private haladesign.swingStyle.TextField txtSoLuong;
    private haladesign.swingStyle.TextField txtTenBienThe;
    private haladesign.swingStyle.TextField txtThuongHieu;
    // End of variables declaration//GEN-END:variables
}
