package haladesign.swing.table;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author NONG HOANG VU
 */
public class PenalAction3 extends javax.swing.JPanel {

    /**
     * Creates new form PenalAction2
     */
    public PenalAction3() {
        initComponents();
    }
    public void initEvent(TableActionEvent1 event, int row) {
        cmdEdit.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.edit(row);
            }
        });
        cmdDetail.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.detail(row);
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdEdit = new haladesign.swing.table.ActionButton();
        cmdDetail = new haladesign.swing.table.ActionButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 0));

        cmdEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haladesign/icon/trash-can.png"))); // NOI18N
        add(cmdEdit);

        cmdDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haladesign/icon/eye.png"))); // NOI18N
        cmdDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDetailActionPerformed(evt);
            }
        });
        add(cmdDetail);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private haladesign.swing.table.ActionButton cmdDetail;
    private haladesign.swing.table.ActionButton cmdEdit;
    // End of variables declaration//GEN-END:variables
}
